# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernelWeightsOneCPP <- function(x, xgrid, bw, kernel = "gaussian") {
    .Call(`_smoothemplik_kernelWeightsOneCPP`, x, xgrid, bw, kernel)
}

kernelWeightsCPP <- function(x, xgrid, bw, kernel = "gaussian") {
    .Call(`_smoothemplik_kernelWeightsCPP`, x, xgrid, bw, kernel)
}

kernelDensityCPP <- function(x, xgrid, bw, kernel = "gaussian") {
    .Call(`_smoothemplik_kernelDensityCPP`, x, xgrid, bw, kernel)
}

kernelSmoothCPP <- function(x, y, xgrid, bw, kernel = "gaussian", LOO = FALSE) {
    .Call(`_smoothemplik_kernelSmoothCPP`, x, y, xgrid, bw, kernel, LOO)
}

