# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

brentMin <- function(f, lower, upper, tol = 1e-8, maxiter = 200L) {
    .Call(`_smoothemplik_brentMin`, f, lower, upper, tol, maxiter)
}

brentZero <- function(f, lower, upper, tol = 1e-8, maxiter = 100L) {
    .Call(`_smoothemplik_brentZero`, f, lower, upper, tol, maxiter)
}

#' @importFrom RcppParallel RcppParallelLibs
NULL

kernelFunCPP <- function(x, kernel, order, convolution = FALSE) {
    .Call(`_smoothemplik_kernelFunCPP`, x, kernel, order, convolution)
}

kernelWeightsOneCPP <- function(x, xout, bw, kernel = "gaussian", order = 2L, convolution = FALSE) {
    .Call(`_smoothemplik_kernelWeightsOneCPP`, x, xout, bw, kernel, order, convolution)
}

sparseKernelWeightsOneCPP <- function(x, xout, bw, kernel = "gaussian", order = 2L, convolution = FALSE) {
    .Call(`_smoothemplik_sparseKernelWeightsOneCPP`, x, xout, bw, kernel, order, convolution)
}

kernelWeightsCPP <- function(x, xout, bw, kernel = "gaussian", order = 2L, convolution = FALSE) {
    .Call(`_smoothemplik_kernelWeightsCPP`, x, xout, bw, kernel, order, convolution)
}

sparseKernelWeightsCPP <- function(x, xout, bw, kernel = "gaussian", order = 2L, convolution = FALSE) {
    .Call(`_smoothemplik_sparseKernelWeightsCPP`, x, xout, bw, kernel, order, convolution)
}

kernelDensityCPP <- function(x, xout, weights, bw, kernel = "gaussian", order = 2L, convolution = FALSE, chunks = 0L) {
    .Call(`_smoothemplik_kernelDensityCPP`, x, xout, weights, bw, kernel, order, convolution, chunks)
}

kernelSmoothCPP <- function(x, y, xout, weights, bw, kernel = "gaussian", order = 2L, LOO = FALSE, convolution = FALSE, chunks = 0L) {
    .Call(`_smoothemplik_kernelSmoothCPP`, x, y, xout, weights, bw, kernel, order, LOO, convolution, chunks)
}

